A02 straight line x86
danyaberezun/compilers-supplementary pull request #1217
Opened 2024-02-08 10:20 UTC by ilma4

2024-02-13 09:07 UTC, e2e4b6b7 requested changes

2024-02-13 09:07 UTC, e2e4b6b7 commented on src/X86.lama
> +    | "&&" -> code <+ Binop("!!", b, eax) <+ Set("ne", "%al")<+ Binop("&&", L(1), eax) <+ Mov(eax, res)
1 && 2 will result false as far as I understood this code. This is incorrect, you have to normalize the int value

2024-02-13 09:07 UTC, e2e4b6b7 commented on src/X86.lama
> +    | _ -> failure("codegeneration for BINOP %s is not yet implemented\n", s.string)
where is `!!`?

2024-02-13 09:15 UTC, e2e4b6b7 commented on src/X86.lama
> +    code := code <+ Mov(a, eax);
Sorry for spamming. This instruction is redundant for most of cases (imperformant)

2024-02-13 13:19 UTC, ilma4 commented on src/X86.lama
> +    | "&&" -> code <+ Binop("!!", b, eax) <+ Set("ne", "%al")<+ Binop("&&", L(1), eax) <+ Mov(eax, res)
1 && 2 will result true as expected. The issue is 1 && 0 will result true as well.
Fixed in the next commits

2024-02-23 18:38 UTC, e2e4b6b7 requested changes

2024-02-23 18:38 UTC, e2e4b6b7 commented on src/SM.lama
> +          | _ -> failure("Error in SM.eval: can't read from world while READ") esac
nit: Actually, this case is impossible as the function return pair

2024-02-23 18:38 UTC, e2e4b6b7 commented on src/X86.lama
> +    | "*" -> code <+ Mov(a, eax) <+ Binop(op, b, eax) <+ Mov(eax, a)
nit: Still redundant move if a and b both in registers

2024-02-23 18:38 UTC, e2e4b6b7 commented on src/X86.lama
> +    emptyBuffer() <+ Binop("^", eax, eax) <+ Binop("!!", b, a) <+ Set("ne", "%al") <+ Mov(eax, a)
It works but not follows the specification. The resulting value have to be zero or one AFAIK, not an arbitrary integer

2024-02-23 18:38 UTC, e2e4b6b7 commented on src/X86.lama
> +  emptyBuffer() <+ Binop("^", eax, eax) <+ cmpWithZeroInsn(a) <+ Set("ne", "%al")
edx is not cleared but used as "%dl"

2024-02-23 18:38 UTC, e2e4b6b7 commented on src/X86.lama
> +    emptyBuffer() <+ Mov(a, eax) <+ Binop("cmp", b, eax) <+ Set(suffix(op), "%al") <+ Binop("&&", L(1), eax) <+ Mov(eax, a)
This does not work. You have `a` in eax and then assigning result to the lowest bits of "%al". But you still have something unexpected in the highest bits

2024-02-23 19:36 UTC, ilma4 commented on src/X86.lama
> +    emptyBuffer() <+ Binop("^", eax, eax) <+ Binop("!!", b, a) <+ Set("ne", "%al") <+ Mov(eax, a)
I believe, it follows. First, eax is zeroed. Then "setne" sets the least byte to zero or one (the greater bits to zero and the least bit to 1/0). So it is exactry zero or one

2024-02-23 19:40 UTC, ilma4 commented on src/X86.lama
> +    emptyBuffer() <+ Mov(a, eax) <+ Binop("cmp", b, eax) <+ Set(suffix(op), "%al") <+ Binop("&&", L(1), eax) <+ Mov(eax, a)
So I clear it with bitwise && next operation, but only higher bits

2024-02-28 09:09 UTC, e2e4b6b7 commented
Okey, you are right in all comments. It is quite unique solution, but correct as far as I understand

2024-02-28 09:09 UTC, closed without merging