A02 Aleksei Beliaev
danyaberezun/compilers-supplementary pull request #1220
Opened 2024-02-08 11:47 UTC by Alexeyha

2024-02-13 09:23 UTC, e2e4b6b7 requested changes

2024-02-13 09:23 UTC, e2e4b6b7 commented on src/X86.lama
> +  if (stackOpnd(x)) then [env.push(y), code <+ Mov (x, eax) <+ Binop ("^", edx, edx) <+ Binop ("cmp", eax, y) <+ Set (suffix(op), "%dl") <+ Mov (edx, y)]
`cmp`, `and`, `or` instructions allows for one operand to be a memory operand. So you may have a situation where y is register while x is stack and it may be compiled better

2024-02-13 09:23 UTC, e2e4b6b7 commented on src/X86.lama
> +  if (stackOpnd(x)) then [env.push(y), code <+ Mov (x, eax) <+ Binop (op, eax, y)]
Same

2024-02-13 09:23 UTC, e2e4b6b7 commented on src/X86.lama
> +                        if (stackOpnd(x)) then [env.push(y), code <+ Mov (x, eax) <+ Binop (op, eax, y)]
same

2024-02-13 09:23 UTC, e2e4b6b7 commented on src/X86.lama
> +  if (stackOpnd(opnd)) then [env, code <+ Binop ("^", edx, edx) <+ Mov (opnd, eax) <+ Binop ("cmp", L (0), eax) <+ Set (suffix("!="), "%dl") <+ Mov (edx, opnd)]
Same, because it is allowed to execute cmp with immediate operand and stack operand

2024-02-13 11:01 UTC, e2e4b6b7 commented on src/X86.lama
> +  if (stackOpnd(x)) then [env.push(y), code <+ Mov (x, eax) <+ Binop (op, eax, y)]
Still? Why not the same as addition?

2024-02-13 11:17 UTC, Alexeyha commented on src/X86.lama
> +  if (stackOpnd(x)) then [env.push(y), code <+ Mov (x, eax) <+ Binop (op, eax, y)]
imul is the destination-size operator, so it must be a register. Btw it's not a final version

2024-02-13 11:40 UTC, Alexeyha commented on src/X86.lama
> +  if (stackOpnd(x)) then [env.push(y), code <+ Mov (x, eax) <+ Binop ("^", edx, edx) <+ Binop ("cmp", eax, y) <+ Set (suffix(op), "%dl") <+ Mov (edx, y)]
Fixed it, now special operator for imull (because it requires register dest), therefore I change the order of operands in this case, sorry for the naming)0)

2024-02-18 12:49 UTC, e2e4b6b7 approved these changes
Nice job regarding imul

2024-02-18 12:49 UTC, e2e4b6b7 commented on src/X86.lama
> +  elif (stackOpnd(y)) then [env.push(x), code <+ Binop (op, y, x)]
This case is incorrect. You will have a result in x which is not as expected. It works just because it is never triggered. I guess you should add Mov (x, y)

2024-02-18 12:49 UTC, e2e4b6b7 commented on src/X86.lama
> +  if (stackOpnd(x) && stackOpnd(y)) then [env.push(y), code <+ Mov (y, edx) <+ Binop (op, x, edx) <+ Mov (edx, y)]
Hm. Nobody did it this way. According to the docs, you are right. But none of them fails in the tests. Hmmmmmmm. Okay

2024-02-18 12:49 UTC, closed without merging