[CUB] Dmitrii Artiukhov A02
danyaberezun/compilers-supplementary pull request #1223
Opened 2024-02-08 15:53 UTC by dmitrii-artuhov

2024-02-13 10:51 UTC, e2e4b6b7 requested changes

2024-02-13 10:51 UTC, e2e4b6b7 commented on src/X86.lama
> +    "/" -> [env.push(y), code <+ Mov (y, eax) <+ IDiv (x) <+ Mov (eax, y)]
Cltd

2024-02-13 10:51 UTC, e2e4b6b7 commented on src/X86.lama
> +    if stackOpnd(pos) then [env.push(pos), code <+ Mov(L (0), edx) <+ Mov (pos, eax) <+ Binop ("cmp", L (0), eax) <+ Set (suffix("!="), dl) <+ Mov (edx, pos)]
redundant branch. cmp allows to compare immediate operand with memory location

2024-02-13 10:51 UTC, e2e4b6b7 commented on src/X86.lama
> +  if (stackOpnd(x)) then [env.push(y), code <+ Mov (L (0), edx) <+ Mov (x, eax) <+ Binop ("cmp", eax, y) <+ Set (suffix(op), dl) <+ Mov (edx, y)]
if x is stack operand and y is in register, the move is redundant

2024-03-09 12:47 UTC, e2e4b6b7 commented
Fix this task until the end of Monday or it will considered as failed

2024-03-11 19:01 UTC, dmitrii-artuhov commented on src/X86.lama
> +    "/" -> [env.push(y), code <+ Mov (y, eax) <+ IDiv (x) <+ Mov (eax, y)]
done

2024-03-11 19:07 UTC, dmitrii-artuhov commented on src/X86.lama
> +    if stackOpnd(pos) then [env.push(pos), code <+ Mov(L (0), edx) <+ Mov (pos, eax) <+ Binop ("cmp", L (0), eax) <+ Set (suffix("!="), dl) <+ Mov (edx, pos)]
done

2024-03-12 00:26 UTC, closed without merging