A04 Aleksei Beliaev
danyaberezun/compilers-supplementary pull request #1251
Opened 2024-02-15 19:56 UTC by Alexeyha

2024-02-18 12:57 UTC, e2e4b6b7 requested changes

2024-02-18 12:57 UTC, e2e4b6b7 commented on src/Stmt.lama
> +  | While (expr, stmt1) -> while (evalExpr(c.fst, expr)) do c := eval(c, stmt1) od; c
nit: if + recursion is more funcional

2024-02-19 19:10 UTC, Alexeyha commented on src/Stmt.lama
> +  | While (expr, stmt1) -> while (evalExpr(c.fst, expr)) do c := eval(c, stmt1) od; c
.... fixed

2024-02-19 19:10 UTC, Alexeyha commented on src/SM.lama
> +            [_, env, s2Code] -> [false, env, compileExpr(e) <+ CJMP ("z", lab1) <+> s1Code <+ JMP (lab2) <+ LABEL (lab1) <+> s2Code <+ LABEL (lab2)]
fixed

2024-02-19 19:10 UTC, Alexeyha commented on src/SM.lama
> +          [lab1, lab2, env1] -> case compile(lab, env1, s) of
fixed

2024-02-19 19:10 UTC, Alexeyha commented on src/SM.lama
> +        [lab1, env] -> case compile(lab, env, s) of
fixed

2024-03-09 13:14 UTC, e2e4b6b7 requested changes

2024-03-09 13:14 UTC, e2e4b6b7 commented on src/SM.lama
> +          [lab1Used, env, sCode] -> [lab1Used, env, singletonBuffer(LABEL (lab1)) <+> sCode <+> compileExpr(expr) <+ CJMP ("nz", lab1)]
Now the end of body is the beginning of the body. You will skip the check of the condition for the end of loop and end up with the infinite loop

Also you are returning if the lab1 were used which is not the provided lab. Provided lab is unconditionally unused as for the while loop

2024-03-10 15:44 UTC, Alexeyha commented on src/SM.lama
> +          [lab1Used, env, sCode] -> [lab1Used, env, singletonBuffer(LABEL (lab1)) <+> sCode <+> compileExpr(expr) <+ CJMP ("nz", lab1)]
Oh yes, it was not a problem, when I didn't reuse labels in `if`. Thank you!!
Fixed

2024-04-10 03:52 UTC, closed without merging