A04, Zaitsev Iurii
danyaberezun/compilers-supplementary pull request #1254
Opened 2024-02-18 08:15 UTC by Hello-zoka

2024-02-18 12:04 UTC, e2e4b6b7 requested changes

2024-02-18 12:04 UTC, e2e4b6b7 commented on src/X86.lama
> +              "Z" -> [env, code <+> move(L(0), eax) <+ Binop("cmp", s, eax) <+ CJmp("z", l)]
nit: by using "z" and "nz" on the SM as well as for X86, you could just compile it as `CJmp(c, l)`

2024-02-18 12:31 UTC, e2e4b6b7 commented on src/X86.lama
> +              "Z" -> [env, code <+> move(L(0), eax) <+ Binop("cmp", s, eax) <+ CJmp("z", l)]
`Binop("cmp", s, L(0))`

2024-02-19 05:43 UTC, Hello-zoka commented on src/SM.lama
> +             case compile (lab, env, s) of
What do you mean? Can you please explain it a little more detailed

2024-02-19 05:54 UTC, Hello-zoka commented on src/X86.lama
> +              "Z" -> [env, code <+> move(L(0), eax) <+ Binop("cmp", s, eax) <+ CJmp("z", l)]
we have to make cmp using register here. In other cases we will face type mismatch when comparing with constant

2024-03-09 13:30 UTC, e2e4b6b7 commented on src/X86.lama
> +              "Z" -> [env, code <+> move(L(0), eax) <+ Binop("cmp", s, eax) <+ CJmp("z", l)]
Hmmmm, why does it work now... Now you have uppercase Z and NZ in assembler.... Actually, assembly is case-insensitive, so it is fine

2024-03-09 13:37 UTC, e2e4b6b7 commented on src/X86.lama
> +              "Z" -> [env, code <+> move(L(0), eax) <+ Binop("cmp", s, eax) <+ CJmp("z", l)]
Did you tested this? AFAIK from the spec it is allowed (https://www.felixcloutier.com/x86/cmp). Maybe they have to be in another order `Binop("cmp", L(0), s)` (lots of instructions are inverted their arguments in different asm syntax)

2024-03-09 13:47 UTC, e2e4b6b7 commented on src/SM.lama
> +             case compile (lab, env, s) of
when you compiling an expression `s` using `compile (lab, env, s)` it means that if `s` decided at some point of time that it would like to jump to the end of it's execution, it may jump to `lab` label (f.e. first branch in if statement). And in this place it means that it will jump outside of do-while loop as `lab` is the label that were provided as the end of this loop. f.e. for this code:
```
do 
  if true then
    write (1)
  fi
while true od
```
you will have only one printed `1`, as then you will do `JMP(lab)` from `SM.lama:177` line and jump out of loop

2024-03-14 01:43 UTC, Hello-zoka commented on src/X86.lama
> +              "Z" -> [env, code <+> move(L(0), eax) <+ Binop("cmp", s, eax) <+ CJmp("z", l)]
Tbh, it's a mystery for me. In case of not storing it in register I am getting such error `*** FAILURE: match failure at Buffer.lama:41:12, value 'Binop ("cmp", L (0), R (0))'
`

2024-03-14 01:57 UTC, Hello-zoka commented on src/SM.lama
> +             case compile (lab, env, s) of
Oh, I've got it. Fixed starting from HW06

2024-03-14 07:24 UTC, e2e4b6b7 commented on src/X86.lama
> +              "Z" -> [env, code <+> move(L(0), eax) <+ Binop("cmp", s, eax) <+ CJmp("z", l)]
[Buffer.lama:41](https://github.com/PLTools/Lama/blob/904b1aa9b140a16642b95f3a75a95e710b8ca160/stdlib/Buffer.lama#L41)

This issue is about `<+>` and `<+`. 

`move(L(0), eax)` returning Buffer, so you have to append it using `<+>`, while `Binop(...)` is only a single element, so have to be appended using `<+`

2024-04-10 04:00 UTC, closed without merging