[NUP] Vsevolod Vaskin
danyaberezun/compilers-supplementary pull request #1302
Opened 2024-03-06 18:21 UTC by Seva-Vaskin

2024-03-09 22:37 UTC, e2e4b6b7 requested changes

2024-03-09 22:37 UTC, e2e4b6b7 commented on src/X86.lama
> +              fi
Utilize pattern matching

2024-03-09 22:37 UTC, e2e4b6b7 commented on src/X86.lama
> +                  then [env.push(y), code <+ Mov (x, eax) <+ Binop (op, eax, y) <+ Mov (eax, y)]
Last Mov is redundant and i guess incorrect

2024-03-09 22:37 UTC, e2e4b6b7 commented on src/X86.lama
> +                                    <+ Binop(op, eax, edx) <+ Mov (edx, y)]
these operations could be optimized if one of the operands is in register

2024-03-10 08:18 UTC, Seva-Vaskin commented on src/X86.lama
> +                  then [env.push(y), code <+ Mov (x, eax) <+ Binop (op, eax, y) <+ Mov (eax, y)]
Binop puts the result into a register, so the last Mov pushes the result from the register onto the stack. I don't understand what's wrong

2024-03-10 08:37 UTC, Seva-Vaskin commented on src/X86.lama
> +                  then [env.push(y), code <+ Mov (x, eax) <+ Binop (op, eax, y) <+ Mov (eax, y)]
Ok, I tried to delete the lask Mov and it still works... So, is it true that binop puts the result in y?

2024-03-10 09:24 UTC, Seva-Vaskin commented on src/X86.lama
> +                                    <+ Binop(op, eax, edx) <+ Mov (edx, y)]
Done

2024-03-10 09:26 UTC, Seva-Vaskin commented on src/X86.lama
> +              fi
I changed `if` to `case` in some places.
Since we were told at the lecture that pattern matching does not work for multiple matching, I did not make the replacement everywhere to avoid copy-paste

2024-03-12 00:36 UTC, e2e4b6b7 commented on src/X86.lama
> +              fi
You should extract most of this code into functions and then copy-paste only functions call

2024-03-12 00:37 UTC, e2e4b6b7 commented on src/X86.lama
> +                                              <+ Binop(op, eax, edx) <+ Mov (edx, y)]
Format asm instructions in a better way, one per line preferably

2024-03-12 00:38 UTC, closed without merging