[NUP] A06 Vsevolod Vaskin
danyaberezun/compilers-supplementary pull request #1406
Opened 2024-04-08 20:33 UTC by Seva-Vaskin

2024-04-20 03:52 UTC, e2e4b6b7 requested changes

2024-04-20 03:52 UTC, e2e4b6b7 commented on src/Expr.lama
> +    | Const (x) -> [c, x]
wrap in Var

2024-04-20 03:52 UTC, e2e4b6b7 commented on src/X86.lama
> +                  esac
❤️

2024-05-17 18:20 UTC, e2e4b6b7 commented
ping

2024-05-25 15:36 UTC, Seva-Vaskin commented
Fixed

2024-05-25 18:43 UTC, e2e4b6b7 approved these changes

2024-05-25 18:43 UTC, closed without merging